### ISSUE TITLE
Unable to connect to VTS API 

### ISSUE THREAD

**Issue by chiveswang** [satetsu888/vts-chameleon#2]
**Describe the bug**
Unable to connect to VTS API , VTS chameleon keep searching but no effect.

**To Reproduce**
1. Open VTube Studio & Start API(Allow plugin) with defaults
2. Open VTS chameleon
3. See error

**Expected behavior**
Connecting Successful

**Screenshots**
![image](https://user-images.githubusercontent.com/102021479/159228058-21ae55fe-46f4-4ddb-a7f2-6b245afc839e.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Version 10 19042.1586

 - VTube Studio Version: 1.18.0
 - VTS-chameleon Version: 0.0.9

**Additional context**
In the screenshot, I try to open another plugin "karasubonk" and it can be connect successfully

**Comment by satetsu888** [comment]
Thank you for detailed reporting the issue!

This situation can be occurred if vts-chameleon don't receive the udp packet from VTube Studio.
I assume windows or any softwares like anti-virus prevent access to local network by either vts-chameleon or VTube Studio.
so, please try checking  these software's settings especially networking.

I did implement only auto detection for VTube Studio, because manual host, port setting could cause some issues...
But Now, I think this plugin should have manual connection  feature by specify host and port.

**Comment by satetsu888** [comment]
I apologize for the long wait.

With the recently updated v0.0.10, we have enabled the ability to connect to localhost:8001 regardless of whether UDP packets are present or not.

The above should address the issue, but if you encounter any problems, please reopen this issue.
